org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.java.home=E:/Program Files/Java/jdk-17

minecraft_version=1.20.1
forge_version=47.4.22
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1
mod_id=yaoguang
mod_name=Yaoguang
mod_version=1.0.0
mod_group_id=com.fish.yaoguang
mod_authors=fish
mod_description=光线追踪